language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -e . --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=pyramid_persona setup.py test
after_success:
  - coveralls
